package com.glodon.gdmp.dao.portal;

import com.glodon.gdmp.model.portal.PortalHomeImage;
import java.util.List;

public interface PortalHomeImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_home_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_home_image
     *
     * @mbg.generated
     */
    int insert(PortalHomeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_home_image
     *
     * @mbg.generated
     */
    PortalHomeImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_home_image
     *
     * @mbg.generated
     */
    List<PortalHomeImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_home_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PortalHomeImage record);
}