package com.glodon.gdmp.dao.portal;

import com.glodon.gdmp.model.portal.PortalGovernmentOpen;
import java.util.List;

public interface PortalGovernmentOpenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_government_open
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_government_open
     *
     * @mbg.generated
     */
    int insert(PortalGovernmentOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_government_open
     *
     * @mbg.generated
     */
    PortalGovernmentOpen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_government_open
     *
     * @mbg.generated
     */
    List<PortalGovernmentOpen> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_government_open
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PortalGovernmentOpen record);
}