package com.glodon.gdmp.dao.app;

import com.glodon.gdmp.model.app.AffirmConclusion;
import java.util.List;

public interface AffirmConclusionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affirm_conclusion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affirm_conclusion
     *
     * @mbg.generated
     */
    int insert(AffirmConclusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affirm_conclusion
     *
     * @mbg.generated
     */
    AffirmConclusion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affirm_conclusion
     *
     * @mbg.generated
     */
    List<AffirmConclusion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table affirm_conclusion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AffirmConclusion record);
}