package com.glodon.gdmp.dao.app;

import com.glodon.gdmp.model.app.AssessmentExplain;
import java.util.List;

public interface AssessmentExplainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment_explain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment_explain
     *
     * @mbg.generated
     */
    int insert(AssessmentExplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment_explain
     *
     * @mbg.generated
     */
    AssessmentExplain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment_explain
     *
     * @mbg.generated
     */
    List<AssessmentExplain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assessment_explain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AssessmentExplain record);
}