package com.glodon.gdmp.dao.app;

import com.glodon.gdmp.model.app.HouseBasicInformation;
import java.util.List;

public interface HouseBasicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_basic_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_basic_information
     *
     * @mbg.generated
     */
    int insert(HouseBasicInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_basic_information
     *
     * @mbg.generated
     */
    HouseBasicInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_basic_information
     *
     * @mbg.generated
     */
    List<HouseBasicInformation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_basic_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HouseBasicInformation record);
}